---
version: "3"


services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true
    volumes:
      - /home/administrateur/docker/jackett/config:/config
      - /home/administrateur/docker/torrents/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/administrateur/docker/radarr/config:/config
      - /home/administrateur/docker/videos/movies:/movies
      - /home/administrateur/docker/torrents/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
 
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/administrateur/docker/sonarr/config:/config
      - /home/administrateur/docker/videos/tv:/tv
      - /home/administrateur/docker/torrents/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - 8191:8191
    restart: unless-stopped
  
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=username
      - PASS=password
    volumes:
      - /home/administrateur/docker/transmission/config:/config
      - /home/administrateur/docker/torrents/downloads:/downloads
      - /home/administrateur/docker/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - JELLYFIN_PublishedServerUrl=192.168.5.112 
    volumes:
      - /home/administrateur/docker/jellyfin/config:/config
      - /home/administrateur/docker/videos/tv:/data/tvshows
      - /home/administrateur/docker/videos/movies:/data/movies
      - /home/administrateur/docker/jellyfin/lib:/opt/vc/lib
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
